### ISSUE TITLE
IndexError: The shape of the mask [2, 3, 256, 256] at index 1 does not match the shape of the indexed tensor [2, 1, 256, 256] at index 1

### ISSUE THREAD

**Issue by yjwong1999** [mazurowski-lab/segmentation-guided-diffusion#13]
Dear @nickk124 

First of all, congratulations on your work for being accepted by MICCAI 2024! This is a very wonderful work by your team.
I am trying to train my custom segmentation-guided model using the provided codes.
Basically, I follow your [guide](https://github.com/mazurowski-lab/segmentation-guided-diffusion?tab=readme-ov-file#2b-train-your-own-models) on the README to prepare my own dataset.
However, I get the following error when trying to run the segmentation-guided model.

> IndexError: The shape of the mask [2, 3, 256, 256] at index 1 does not match the shape of the indexed tensor [2, 1, 256, 256] at index 1

When I set the `--num_img_channels 1`, then this error is gone.
I believe this error arises because I try to map a grayscale mask to RGB image.
Is it possible to add support such that we can map a grayscale mask to RGB image?

Thanks a lot! Really appreciate the open-source contribution.

**Comment by nickk124** [comment]
Hi, can you provide the line of code that is returning that error, as well as the full error stack?
Thanks!

**Comment by yjwong1999** [comment]
Hi, thanks for the reply!

Firstly, I run the following training command
```
CUDA_VISIBLE_DEVICES=0 python3 main.py \
    --mode train \
    --model_type DDIM \
    --img_size 256 \
    --num_img_channels 3 \
    --dataset custom_data\
    --img_dir data \
    --seg_dir mask \
    --segmentation_guided \
    --num_segmentation_classes 2 \
    --train_batch_size 2 \
    --eval_batch_size 2 \
    --num_epochs 1
```

Then, I get the following error

> File "main.py", line 418, in <module>
>     main(
>   File "main.py", line 341, in main
>     train_loop(
>   File "/home/yj/segmentation-guided-diffusion/training.py", line 103, in train_loop
>     noisy_images = add_segmentations_to_noise(noisy_images, batch, config, device)
>   File "/home/yj/segmentation-guided-diffusion/eval.py", line 356, in add_segmentations_to_noise
>     segs = convert_segbatch_to_multiclass(noisy_images.shape, segmentations_batch, config, device) 
>   File "/home/yj/segmentation-guided-diffusion/eval.py", line 316, in convert_segbatch_to_multiclass
>     segs[segs == 0] = seg[segs == 0]
> IndexError: The shape of the mask [2, 3, 256, 256] at index 1 does not match the shape of the indexed tensor [2, 1, 256, 256] at index 1

FYI, my images in the img_dir is RGB, while my masks in the mask_dir is grayscale (row x col). For the mask, 0 is background and 1 is the object I want (single class). 

So far I am able to run the code if I set ```--num_img_channels 1```, but not when I set ```--num_img_channels 3```. 

Please let me know if you have any idea on resolving this issue.
Thanks a lot!

**Comment by nickk124** [comment]
Hi,

Thanks for your patience! I did some investigating and the bug is in how the segmentations are being loaded before being supplied to the model. I committed a fix at https://github.com/mazurowski-lab/segmentation-guided-diffusion/commit/53acdbeab1a53c766e687c8fe54c9da551d7a07f. Could you try the most recent fix and let me know if you're still having problems?

**Comment by yjwong1999** [comment]
Hi @nickk124 

Thank you so much for the updates!
I read thru the updated the code, and it makes perfect sense now!
Meanwhile, I think [line 287 of main.py](https://github.com/mazurowski-lab/segmentation-guided-diffusion/blob/53acdbeab1a53c766e687c8fe54c9da551d7a07f/main.py#L287) needed to be fixed.

Currently, the code is:
```
    # define the model
    in_channels = num_img_channels
    if config.segmentation_guided:
        assert config.num_segmentation_classes is not None
        assert config.num_segmentation_classes > 1, "must have at least 2 segmentation classes (INCLUDING background)" 
        if config.segmentation_channel_mode == "single":
            in_channels = 2
        elif config.segmentation_channel_mode == "multi":
            in_channels = len(seg_types) + 1
```

When I am using RGB images with segmentation guidance, the ` in_channels = 2` will overwrite the input channels for diffusion model as 2, which cannot take the RGB image + mask as input. I think your dataset is mostly grayscale image with grayscale mask, that's why you set ` in_channels = 2`.

Instead, I think we can update [line 287 of main.py](https://github.com/mazurowski-lab/segmentation-guided-diffusion/blob/53acdbeab1a53c766e687c8fe54c9da551d7a07f/main.py#L287) as:
`        if config.segmentation_channel_mode == "single":`
`            in_channels += 1`

Since `in_channels = num_img_channels`, we just have to `in_channels += 1` to add one more dimension to the channel. 

With your updated codes + this tiny fix, I am able to run your model for both RGB image + grayscale mask, and also grayscale image + grayscale mask! Let me know if this fix is useful!

Thanks again for the helpful response!

**Comment by nickk124** [comment]
Hi, 

Thanks for the fix, I just implemented it in https://github.com/mazurowski-lab/segmentation-guided-diffusion/commit/b0a444760005284e2fa81d8764a7f21cae48e5aa. And my apologies for the bugs, this code was mostly tested for medical/greyscale images and didn't receive sufficient testing for RGB.

Since you said this change fixed your issue, I'll go ahead and close this. Thanks!
