### ISSUE TITLE
3D capability

### ISSUE THREAD

**Issue by bwittmann** [mazurowski-lab/segmentation-guided-diffusion#14]
Nice work!

I am asking myself whether your method would also be able to generate 3D images.
Did you experiment with this? What are in your opinion possible bottlenecks?

Best,
Bastian

**Comment by nickk124** [comment]
Hi,

Currently the code can accept images of any number of channels via the `--num_img_channels` argument of main.py, where here we could treat the 3D image slices as just channels, as long as you save each 3D image as a numpy `.npy` array.

But, the code isn't currently built for 3D segmentations; only 2D masks that apply to all of the channels. However, I think that this should be a relatively straightforward update. I'll implement it as soon as I get the chance.
