### ISSUE TITLE
Minor error - seg_paths_train and seg_paths_eval not defined in else statements of main.py

### ISSUE THREAD

**Issue by lukalafaye** [mazurowski-lab/segmentation-guided-diffusion#8]
You should move `seg_paths_train = {}` and `seg_paths_eval = {}` before the if/else statements in lines 93 and 103 of  `main.py`. Otherwise the else statements will throw an undefined error for these dictionaries.

Thanks anyways for the project!

**Comment by nickk124** [comment]
Thanks for the catch :) this has just been fixed in commit 404cebb69a51d714f152715958ce394e3e8f0258. Please let me know if you're still having problems!

Cheers
